apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre  
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
          - name:  POSTGRES_PASSWORD
            value: "juninho27"   
          - name:   POSTGRES_USER
            value: "kubenews_junior"
          - name: POSTGRES_DB
            value: "kubenews_fofoquinha"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports: 
  - port: 5432  
    targetPort: 5432
---    
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: kubenews 
spec: 
  replicas: 20
  selector:
    matchLabels:
      app: kubenews 
  template:
    metadata:
      labels: 
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: juniormarques/kube-news:v1 
        env: 
        - name: DB_DATABASE    
          value: "kubenews_fofoquinha"
        - name: DB_USERNAME  
          value: "kubenews_junior"
        - name: DB_PASSWORD     
          value: "juninho27"
        - name: DB_HOST     
          value: "postgre"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: kube-news 
spec:
  selector:
    app: kubenews 
  ports: 
  - port: 80
    targetPort: 8080
    nodePort: 30000  
  type: LoadBalancer 


